import { StyleSheet } from "react-native";
export default StyleSheet.create({
    page:{
        flex:1,
        width:"100%",
        paddingVertical:30,
        padding:10
    },
    name:{
        fontSize:24,
        fontWeight:"600",
        marginVertical:10
    },
    separator:{
        height:1,
        backgroundColor:"lightgray",
        marginVertical:10,
    },
    row:{
     flexDirection:"row",
     alignItems:"center",
     marginVertical:15,
    },
    quantity:{
     fontSize:25,
     marginHorizontal:20
    },
    button:{
     backgroundColor:"black",
     marginTop:"auto",
     padding:20,
     alignItems:"center"
    },
    buttonText:{
      color:"white",
      fontWeight:"600",
      fontSize:18
    },
    quantityContainer:{
        backgroundColor:"lightgray",
        paddingHorizontal:5,
        paddingVertical:2,
        marginRight:10,
        borderRadius:3
    }
});